"""fix event model

Revision ID: a269e4c8a273
Revises: f6814568c599
Create Date: 2026-05-03 18:39:46.725714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a269e4c8a273'
down_revision: Union[str, Sequence[str], None] = 'f6814568c599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pattern_key', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('raw_message', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_category'), 'event', ['category'], unique=False)
    op.create_index(op.f('ix_event_incident_id'), 'event', ['incident_id'], unique=False)
    op.create_index(op.f('ix_event_pattern_id'), 'event', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_event_pattern_key'), 'event', ['pattern_key'], unique=False)
    op.create_index(op.f('ix_event_severity'), 'event', ['severity'], unique=False)
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_user_id'), 'event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_user_id'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_severity'), table_name='event')
    op.drop_index(op.f('ix_event_pattern_key'), table_name='event')
    op.drop_index(op.f('ix_event_pattern_id'), table_name='event')
    op.drop_index(op.f('ix_event_incident_id'), table_name='event')
    op.drop_index(op.f('ix_event_category'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
