"""initial schema

Revision ID: f47bc9f7ab8f
Revises: 
Create Date: 2026-04-11 14:11:19.739434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47bc9f7ab8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_enabled'), 'analysis', ['enabled'], unique=False)
    op.create_index(op.f('ix_analysis_key'), 'analysis', ['key'], unique=True)
    op.create_index(op.f('ix_analysis_priority'), 'analysis', ['priority'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('pattern_key', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pattern_key', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('raw_message', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_category'), 'event', ['category'], unique=False)
    op.create_index(op.f('ix_event_incident_id'), 'event', ['incident_id'], unique=False)
    op.create_index(op.f('ix_event_pattern_id'), 'event', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_event_pattern_key'), 'event', ['pattern_key'], unique=False)
    op.create_index(op.f('ix_event_severity'), 'event', ['severity'], unique=False)
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_user_id'), 'event', ['user_id'], unique=False)
    op.create_table('history_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('Old_status', sa.String(), nullable=False),
    sa.Column('New_status', sa.String(), nullable=False),
    sa.Column('Changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidenthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidenthistory')
    op.drop_table('history_status')
    op.drop_index(op.f('ix_event_user_id'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_severity'), table_name='event')
    op.drop_index(op.f('ix_event_pattern_key'), table_name='event')
    op.drop_index(op.f('ix_event_pattern_id'), table_name='event')
    op.drop_index(op.f('ix_event_incident_id'), table_name='event')
    op.drop_index(op.f('ix_event_category'), table_name='event')
    op.drop_table('event')
    op.drop_table('comment')
    op.drop_table('incident')
    op.drop_table('user')
    op.drop_index(op.f('ix_analysis_priority'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_key'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_enabled'), table_name='analysis')
    op.drop_table('analysis')
    # ### end Alembic commands ###
