"""make event pattern nullable

Revision ID: f6814568c599
Revises: 3faa75b3f17f
Create Date: 2026-05-03 17:17:32.661828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6814568c599'
down_revision: Union[str, Sequence[str], None] = '3faa75b3f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ppattern_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_event_pattern_id'), table_name='event')
    op.create_index(op.f('ix_event_ppattern_id'), 'event', ['ppattern_id'], unique=False)
    op.drop_constraint(op.f('event_pattern_id_fkey'), 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'analysis', ['ppattern_id'], ['id'])
    op.drop_column('event', 'pattern_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('pattern_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(op.f('event_pattern_id_fkey'), 'event', 'analysis', ['pattern_id'], ['id'])
    op.drop_index(op.f('ix_event_ppattern_id'), table_name='event')
    op.create_index(op.f('ix_event_pattern_id'), 'event', ['pattern_id'], unique=False)
    op.drop_column('event', 'ppattern_id')
    # ### end Alembic commands ###
