DEFAULT_PATTERNS = [
    {
        "key": "db_connection_error",
        "pattern": r"(connection refused|could not connect to database|database connection failed)",
        "severity": "high",
        "message": "Ошибка подключения к базе данных",
        "category": "database",
        "service": "database",
        "enabled": True,
        "priority": 100,
    },
    {
        "key": "db_timeout",
        "pattern": r"(db timeout|database timeout|query timeout)",
        "severity": "medium",
        "message": "Таймаут запроса к базе данных",
        "category": "database",
        "service": "database",
        "enabled": True,
        "priority": 90,
    },
    {
        "key": "auth_invalid_token",
        "pattern": r"(invalid token|token expired|jwt expired|unauthorized)",
        "severity": "medium",
        "message": "Проблема авторизации",
        "category": "auth",
        "service": "auth",
        "enabled": True,
        "priority": 80,
    },
    {
        "key": "permission_denied",
        "pattern": r"(permission denied|forbidden|access denied)",
        "severity": "medium",
        "message": "Недостаточно прав доступа",
        "category": "auth",
        "service": "auth",
        "enabled": True,
        "priority": 75,
    },
    {
        "key": "request_timeout",
        "pattern": r"(request timeout|timed out|timeout exceeded)",
        "severity": "high",
        "message": "Таймаут выполнения запроса",
        "category": "timeout",
        "service": None,
        "enabled": True,
        "priority": 70,
    },
    {
        "key": "validation_error",
        "pattern": r"(validation error|invalid input|bad request|schema validation failed)",
        "severity": "medium",
        "message": "Ошибка валидации входных данных",
        "category": "validation",
        "service": None,
        "enabled": True,
        "priority": 60,
    },
    {
        "key": "external_api_5xx",
        "pattern": r"(502 bad gateway|503 service unavailable|504 gateway timeout)",
        "severity": "high",
        "message": "Ошибка внешнего API",
        "category": "external_api",
        "service": "external_api",
        "enabled": True,
        "priority": 88,
    },
    {
        "key": "memory_error",
        "pattern": r"(out of memory|memoryerror|oom-killer)",
        "severity": "high",
        "message": "Проблема с памятью",
        "category": "system",
        "service": "system",
        "enabled": True,
        "priority": 95,
    },
    {
        "key": "disk_space_low",
        "pattern": r"(no space left on device|disk full|not enough disk space)",
        "severity": "high",
        "message": "Заканчивается место на диске",
        "category": "system",
        "service": "system",
        "enabled": True,
        "priority": 92,
    },
    {
        "key": "generic_error",
        "pattern": r"\berror\b|\bexception\b|\bfailed\b",
        "severity": "high",
        "message": "Общая ошибка приложения",
        "category": "application",
        "service": None,
        "enabled": True,
        "priority": 10,
    },
]